### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by ArchangelaDanzig** [FInnvos123/EliteHIS#1]
EDMC just released v4, which is written in Python 3.x, and I wanted to know if you will be updating EliteHIS to work with the new version. Thank you for your time.

**Comment by fiinnnn** [comment]
Thanks for the heads up, I just added support for EDMC v4.
EDMCOverlay is now no longer included so you'll have to install it separately from [here](https://github.com/inorton/edmcoverlay/releases).
There was one issue with the overlay: https://github.com/inorton/EDMCOverlay/issues/31, so you'll either have to edit the line manually after installing or wait for a new version with the fix.

**Comment by fiinnnn** [comment]
This was just fixed in version [1.0.5](https://github.com/inorton/EDMCOverlay/releases/tag/1.0.5) of EDMCOverlay
